import './global.css';
import { Providers } from './providers';
import Header from '../components/layout/header/Header';
import Footer from '../components/layout/footer/Footer';

export const metadata = {
  title: 'Epicure',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Header />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
