import './global.css';
import { Providers } from './providers';
import Header from '../components/layout/header/Header';
import Footer from '../components/layout/footer/Footer';

export const metadata = {
  title: 'Epicure',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" style={{ margin: 0, padding: 0 }}>
      <body style={{ margin: 0, padding: 0 }}>
        <Providers>
          <div style={{ display: 'flex', flexDirection: 'column', minHeight: '100vh', margin: 0, padding: 0, width: '100%' }}>
            <Header />
            <main style={{ flex: 1, margin: 0, padding: 0, width: '100%' }}>
              {children}
            </main>
            <Footer />
          </div>
        </Providers>
      </body>
    </html>
  );
}
